// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'about', uri: Uri.parse('about'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'lib/app',
    uri: Uri.parse('lib/app'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'notfound',
    uri: Uri.parse('notfound'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'type/[id]',
    uri: Uri.parse('type/[id]'),
    routeBuilder: b6Builder,
  ),
];

const routePaths = (
  path: '/',
  about: '/about',
  lib: (path: '/lib', app: '/lib/app'),
  notfound: '/notfound',
  type: (path: '/type', $id: '/type/[id]'),
);
